{
  "name": "main",
  "inlineText": true,
  "stubModules": [
    "durandal/amd/text"
  ],
  "paths": {
    "text": "durandal/amd/text"
  },
  "baseUrl": "C:\\Users\\Roger\\Documents\\GitHub\\rbdurandal\\Durandal\\skeletons\\vstemplate\\DurandalTemplate\\DurandalTemplate\\App",
  "mainConfigFile": "",
  "include": [
    "main-built",
    "main",
    "text!shell.html",
    "shell",
    "durandal/app",
    "durandal/composition",
    "durandal/events",
    "durandal/http",
    "text!durandal/messageBox.html",
    "durandal/messageBox",
    "durandal/modalDialog",
    "durandal/system",
    "durandal/viewEngine",
    "durandal/viewLocator",
    "durandal/viewModel",
    "durandal/viewModelBinder",
    "durandal/widget",
    "durandal/plugins/router",
    "durandal/transitions/entrance",
    "durandal/widgets/expander/controller",
    "text!durandal/widgets/expander/view.html",
    "Framework_extensions/knockout-extensions",
    "Framework_extensions/viewModelBinderExtensions",
    "rb-plugins/component-b/viewmodels/component-b",
    "text!rb-plugins/component-b/views/component-b.html",
    "rb-plugins/component-x/viewmodels/component-x",
    "text!rb-plugins/component-x/views/component-a.html",
    "rb-plugins/demo/viewmodels/demo",
    "text!rb-plugins/demo/views/demo.html",
    "rb-plugins/flickr/viewmodels/flickr",
    "text!rb-plugins/flickr/views/detail.html",
    "text!rb-plugins/flickr/views/flickr.html",
    "rb-plugins/welcome/viewmodels/welcome",
    "text!rb-plugins/welcome/views/welcome.html",
    "viewmodels/flickr",
    "viewmodels/shell",
    "viewmodels/welcome",
    "text!views/detail.html",
    "text!views/flickr.html",
    "text!views/shell.html",
    "text!views/welcome.html"
  ],
  "exclude": [],
  "keepBuildDir": true,
  "optimize": "uglify2",
  "out": "C:\\Users\\Roger\\Documents\\GitHub\\rbdurandal\\Durandal\\skeletons\\vstemplate\\DurandalTemplate\\DurandalTemplate\\App\\main-built.js",
  "pragmas": {
    "build": true
  }
}